#!/usr/bin/env python
# coding: utf-8

# In[1]:


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import ExtraTreesRegressor, GradientBoostingRegressor, VotingRegressor
from xgboost import XGBRegressor

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(888, 640)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(240, 70, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(250, 120, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(250, 220, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(250, 270, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(250, 320, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(100, 570, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(680, 270, 121, 31))
        self.lineEdit.setFont(self.create_bold_font())
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(680, 320, 121, 31))
        self.lineEdit_2.setFont(self.create_bold_font())
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(680, 120, 121, 31))
        self.lineEdit_3.setFont(self.create_bold_font())
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(680, 370, 121, 31))
        self.lineEdit_5.setFont(self.create_bold_font())
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(250, 170, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(680, 220, 121, 31))
        self.lineEdit_4.setFont(self.create_bold_font())
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(20, 90, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 160, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 230, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(Form)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 300, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_4.setObjectName("radioButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 510, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.radioButton_5 = QtWidgets.QRadioButton(Form)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 370, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_5.setObjectName("radioButton_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(680, 70, 121, 31))
        self.lineEdit_6.setFont(self.create_bold_font())
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(680, 170, 121, 31))
        self.lineEdit_7.setFont(self.create_bold_font())
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(250, 370, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(680, 410, 121, 31))
        self.lineEdit_8.setFont(self.create_bold_font())
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(250, 410, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(440, 560, 341, 51))
        self.lineEdit_9.setFont(self.create_bold_font())
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 490, 891, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(163, -10, 20, 511))
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(self.predict)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ML models UI"))
        self.label.setText(_translate("Form", "Total thickness of layers of FRP wraps (mm):"))
        self.label_2.setText(_translate("Form", "Elastic modulus of FRP (MPa):"))
        self.label_3.setText(_translate("Form", "Yield strength (MPa):"))
        self.label_4.setText(_translate("Form", "Area of concrete core (mm2):"))
        self.label_5.setText(_translate("Form", "Strength of unconfined concrete (MPa):"))
        self.label_9.setText(_translate("Form", "Load carrying capacity (kN):"))
        self.label_11.setText(_translate("Form", "Model selection:"))
        self.label_13.setText(_translate("Form", "Area of steel tube (mm2):"))
        self.radioButton.setText(_translate("Form", "DT"))
        self.radioButton_2.setText(_translate("Form", "ET"))
        self.radioButton_3.setText(_translate("Form", "GB"))
        self.radioButton_4.setText(_translate("Form", "XGB"))
        self.pushButton_2.setText(_translate("Form", "Prediction"))
        self.radioButton_5.setText(_translate("Form", "Voting"))
        self.label_6.setText(_translate("Form", "Eccentric loading ratio:"))
        self.label_7.setText(_translate("Form", "Aspect ratio of elliptical cross section:"))

    def create_bold_font(self):
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        return font

    def predict(self):
        model = None
        if self.radioButton.isChecked():
            model = reg1
        elif self.radioButton_2.isChecked():
            model = reg2
        elif self.radioButton_3.isChecked():
            model = reg3
        elif self.radioButton_4.isChecked():
            model = reg4
        elif self.radioButton_5.isChecked():
            model = ereg

        if model is None:
            self.lineEdit_9.setText("Please select a model.")
            return

        try:
            feature1 = float(self.lineEdit_6.text()) * float(self.lineEdit_3.text())
            feature2 = float(self.lineEdit_7.text()) * float(self.lineEdit_4.text())
            feature3 = float(self.lineEdit.text()) * float(self.lineEdit_2.text())
            feature4 = float(self.lineEdit_5.text())
            feature5 = float(self.lineEdit_8.text())
        except ValueError:
            self.lineEdit_9.setText("Please enter valid input values.")
            return

        features = [[feature1, feature2, feature3, feature4, feature5]]

        prediction = model.predict(features)
        self.lineEdit_9.setText(f"{prediction[0]:.2f}")


if __name__ == "__main__":
    from sklearn.model_selection import train_test_split
    from sklearn.tree import DecisionTreeRegressor
    from sklearn.ensemble import ExtraTreesRegressor, GradientBoostingRegressor, VotingRegressor
    from xgboost import XGBRegressor
    import pandas as pd

    df = pd.read_excel(r"D:\Articles\Isleem\Topic 37\Dataset.xlsx", sheet_name='Dataset', header=0)
    y = df.iloc[:, 5].to_numpy().reshape((-1, 1))
    X = df.iloc[:, [0, 1, 2, 3, 4]].to_numpy()
    Xtr, Xte, ytr, yte = train_test_split(X, y, train_size=0.7, random_state=42)

    reg1 = DecisionTreeRegressor(random_state=0, max_depth=8, min_samples_leaf=1, min_samples_split=2, max_features='sqrt')
    reg2 = ExtraTreesRegressor(n_estimators=200, max_depth=15, min_samples_split=2, min_samples_leaf=1, max_features=None, random_state=0)
    reg3 = GradientBoostingRegressor(learning_rate=0.2, n_estimators=300, max_depth=3, random_state=0)
    reg4 = XGBRegressor(learning_rate=0.3, n_estimators=50, max_depth=3, random_state=0)

    ereg = VotingRegressor(estimators=[('DT', reg1), ('ET', reg2), ('GB', reg3), ('XGB', reg4)])

    reg1.fit(Xtr, ytr)
    reg2.fit(Xtr, ytr)
    reg3.fit(Xtr, ytr)
    reg4.fit(Xtr, ytr)
    ereg.fit(Xtr, ytr)

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())


# In[ ]:




